# Generated by Django 4.0 on 2021-12-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('goal', models.CharField(max_length=200)),
                ('sketch', models.CharField(max_length=100)),
                ('current_state', models.CharField(max_length=3)),
            ],
        ),
    ]
