# Generated by Django 4.0 on 2021-12-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.CharField(default='yes', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='current_state',
            field=models.CharField(max_length=100),
        ),
    ]
