# Generated by Django 4.0 on 2021-12-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_post_published_alter_post_current_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='current_state',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='sketch',
            field=models.CharField(max_length=500),
        ),
    ]
