# Generated by Django 4.0 on 2022-01-02 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_work_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Work',
        ),
    ]
