# Generated by Django 4.0 on 2022-01-03 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main_app', '0010_alter_work_options_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='current_state',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='goal',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='sketch',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='work',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='work',
            name='meal',
            field=models.CharField(choices=[('M', 'Morning'), ('A', 'AfterNoon'), ('N', 'Night')], default='M', max_length=1),
        ),
    ]
