# Generated by Django 4.0 on 2022-01-04 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='meal',
            new_name='tod',
        ),
    ]
