# Generated by Django 4.0 on 2022-01-05 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='progress_pic',
            field=models.URLField(default='https://toppng.com//public/uploads/preview/9d5-badly-drawn-thinking-emoji-11562863577r4jcmmnhf9.png', max_length=250),
        ),
    ]
